# Javier 2023-08-16: Use este para la primera corrida y luego le instale manualmente reformer_pytorch
name: autoformer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  # Nacho extra req
  - wandb
  - seaborn
  - tqdm
  # - cycler # Actually not used
  - pip:
    - torch==1.9.0
    # reformer_pytorch #TODO nacho tiene este en el requirements.txt.

